server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ixxp2024@gmail.com
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    redis:
      host: localhost
cloud:
  aws:
    s3:
      bucket-name:${S3_NAME}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
