spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ip_db
    username: root
    password: 20190976sswu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
    show-sql: true
